services:
  rustbox:
    image: rustbox
    build: ./rustbox
    volumes:
      - ./custom-policy:/usr/src/myapp
    working_dir: /usr/src/myapp
    command:
      - /bin/sh
      -  -c
      - |
        cargo build --target wasm32-wasi --release
        base64 -w0 -i target/wasm32-wasi/release/*.wasm > target/policy_binary.txt
        cat extension-policy-template.yaml target/policy_binary.txt > target/extension-policy.yaml
  httpbin:
    image: kennethreitz/httpbin
    depends_on:
      rustbox:
        condition: service_completed_successfully
    hostname: httpbin
    ports:
      - "80:80"
    networks:
      - flex-gateway-network
  flex-gateway:
    image: flex-gateway-local
    build: ./flex-gateway
    depends_on:
      rustbox:
        condition: service_completed_successfully
      httpbin:
        condition: service_started
    hostname: flex-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./custom-policy/target/extension-policy.yaml:/usr/local/share/mulesoft/flex-gateway/conf.d/extension-policy.yaml
      - ./flex-gateway/api-instance-http-bin.yaml:/usr/local/share/mulesoft/flex-gateway/conf.d/api-instance-http-bin.yaml
      - ./flex-gateway/policy-binding-http-bin-policy.yaml:/usr/local/share/mulesoft/flex-gateway/conf.d/policy-binding-http-bin-policy.yaml
    networks:
      - flex-gateway-network
networks:
  flex-gateway-network: {}
