apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: {{ policyName }}
spec:
  targetRef:
    name: httpbin-example
  policyRef:
    name: {{ policyName }}-implementation
  config:
    header: testheader