apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: log-headers-tls-policy
spec:
  targetRef:
    name: httpbin-tls-example
  policyRef:
    name: log-headers-policy-implementation
  config:
    header: testheader