apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: test-policy-latam
spec:
  targetRef:
    name: httpbin-example
  policyRef:
    name: test-policy-latam-implementation
  config:
    header: testheader